version: '3'
services:
  myservice:
    build: ../example-service
    container_name: "example-service"
    ports:
     - "9091:9091"
  localnginx:
    build: ../nginx
    depends_on:
     - myservice
    ports:
     - "80:80"
    environment:
     - JAVA_BACKEND_HOST=myservice
     - JAVA_BACKEND_PORT=9091


